CREATE TABLE TB_PESSOA
(
	ID_PESSOA INT PRIMARY KEY IDENTITY(1,1),
	NOMECOMPLETO VARCHAR(80) NOT NULL,
	NOMECONHECIDO VARCHAR(80) NOT NULL,
	CPFCNPJ VARCHAR(20),
	RGIE VARCHAR(20),
	ID_PESSOATIPO INT NOT NULL,
	DTNASCIMENTO DATETIME NOT NULL,
	SEXO BIT NOT NULL,
	ARQUIVADO BIT NOT NULL DEFAULT 0,
	ID_USUARIOCADASTRO INT,
	DTCADASTRO DATETIME,
	ID_USUARIOALTERACAO INT,
	DTALTERACAO DATETIME,
	ID_USUARIOARQUIVACAO INT,
	DTARQUIVACAO DATETIME
)

CREATE TABLE TB_PESSOATIPO
(
	ID_PESSOATIPO INT PRIMARY KEY IDENTITY(1,1),
	DESCRICAO VARCHAR(30) NOT NULL UNIQUE,
	ID_USUARIOCADASTRO INT,
	DTCADASTRO DATETIME,
	ID_USUARIOALTERACAO INT,
	DTALTERACAO DATETIME
)

CREATE TABLE TB_CLIENTE
(
	ID_CLIENTE INT PRIMARY KEY IDENTITY(1,1),
	ID_PESSOA INT NOT NULL,
	ID_USUARIOCADASTRO INT,
	DTCADASTRO DATETIME,
)

CREATE TABLE TB_ENDERECO
(
	ID_ENDERECO INT PRIMARY KEY IDENTITY(1,1),
	ID_PESSOA INT NOT NULL,
	LOGRADOURO VARCHAR(200) NOT NULL,
	NUMERO VARCHAR(15) NOT NULL,
	COMPLEMENTO VARCHAR(60),
	BAIRRO VARCHAR(40) NOT NULL,
	CIDADE VARCHAR(40) NOT NULL,
	ESTADO VARCHAR(2) NOT NULL,
	ID_USUARIOCADASTRO INT,
	DTCADASTRO DATETIME,
	ID_USUARIOALTERACAO INT,
	DTALTERACAO DATETIME
)

CREATE TABLE TB_CONTATO
(
	ID_CONTATO INT PRIMARY KEY IDENTITY(1,1),
	ID_PESSOA INT NOT NULL,
	ID_CONTATOTIPO INT NOT NULL,
	DDD TINYINT,
	TELEFONE VARCHAR(15),
	EMAIL VARCHAR(100),
	ID_USUARIOCADASTRO INT,
	DTCADASTRO DATETIME,
	ID_USUARIOALTERACAO INT,
	DTALTERACAO DATETIME
)

CREATE TABLE TB_CONTATOTIPO
(
	ID_CONTATOTIPO INT PRIMARY KEY IDENTITY(1,1),
	DESCRICAO VARCHAR(30) NOT NULL UNIQUE,
	ID_USUARIOCADASTRO INT,
	DTCADASTRO DATETIME,
	ID_USUARIOALTERACAO INT,
	DTALTERACAO DATETIME
)

CREATE TABLE TB_USUARIO
(
	ID_USUARIO INT PRIMARY KEY IDENTITY(1,1),
	LOGIN VARCHAR(25) NOT NULL UNIQUE,
	SENHA VARCHAR(64) NOT NULL,
	ID_PESSOA INT NOT NULL,
	ID_GRUPO INT,
	ID_USUARIOCADASTRO INT,
	DTCADASTRO DATETIME,
	ID_USUARIOALTERACAO INT,
	DTALTERACAO DATETIME
)

CREATE TABLE TB_PERMISSAO
(
	ID_PERMISSAO INT PRIMARY KEY IDENTITY(1,1),
	URL VARCHAR(200) NOT NULL UNIQUE,
	DESCRICAO VARCHAR(30) NOT NULL,
	OBSERVACOES VARCHAR(1000),
	ID_USUARIOCADASTRO INT,
	DTCADASTRO DATETIME,
	ID_USUARIOALTERACAO INT,
	DTALTERACAO DATETIME
)

CREATE TABLE TB_GRUPO
(
	ID_GRUPO INT PRIMARY KEY IDENTITY(1,1),
	DESCRICAO VARCHAR(30) NOT NULL UNIQUE,
	ID_GRUPOTIPO INT NOT NULL,
	ID_USUARIOCADASTRO INT,
	DTCADASTRO DATETIME,
	ID_USUARIOALTERACAO INT,
	DTALTERACAO DATETIME
)

CREATE TABLE TB_GRUPOTIPO
(
	ID_GRUPOTIPO INT PRIMARY KEY IDENTITY(1,1),
	DESCRICAO VARCHAR(30) NOT NULL UNIQUE,
	ID_USUARIOCADASTRO INT,
	DTCADASTRO DATETIME,
	ID_USUARIOALTERACAO INT,
	DTALTERACAO DATETIME
)

CREATE TABLE TB_GRUPOPERMISSAO
(
	ID_GRUPOPERMISSAO INT PRIMARY KEY IDENTITY(1,1),
	ID_GRUPO INT NOT NULL,
	ID_PERMISSAO INT NOT NULL,
	ID_USUARIOCADASTRO INT,
	DTCADASTRO DATETIME,
	ID_USUARIOALTERACAO INT,
	DTALTERACAO DATETIME
)

CREATE TABLE TB_DEPTOTECNICO
(
	ID_DEPTOTECNICO INT PRIMARY KEY IDENTITY(1,1),
	DESCRICAO VARCHAR(30) NOT NULL UNIQUE,
	ID_USUARIOCADASTRO INT,
	DTCADASTRO DATETIME,
	ID_USUARIOALTERACAO INT,
	DTALTERACAO DATETIME
)

CREATE TABLE TB_PEDIDO
(
	ID_PEDIDO INT PRIMARY KEY IDENTITY(1,1),
	ID_PEDIDOTIPO INT NOT NULL,
	ID_PEDIDOSTATUS INT NOT NULL,
	ID_CLIENTE INT NOT NULL,
	ID_TECNICO INT,
	ID_DEPTOTECNICO INT NOT NULL,
	DESCRICAOEQUIPAMENTO VARCHAR(1000) NOT NULL,
	DESCRICAODEFEITO VARCHAR(1000) NOT NULL,
	DESCRICAOSERVICO VARCHAR(1000) NOT NULL,
	DIAGNOSTICOTECNICO VARCHAR(1000),
	NUMSERIEEQUIPAMENTO VARCHAR(100) NOT NULL,
	VALORPECAS FLOAT NOT NULL DEFAULT 0,
	VALORSERVICO FLOAT NOT NULL DEFAULT 0,
	ID_USUARIOCADASTRO INT,
	DTCADASTRO DATETIME,
	DESCRICAOCANCELAMENTO VARCHAR(1000),
	ID_USUARIOCANCELAMENTO INT,
	DTCANCELAMENTO DATETIME,
	ID_USUARIOPGTOCONFIRMADO INT,
	DTPGTOCONFIRMADO DATETIME
)

CREATE TABLE TB_PEDIDOSTATUS
(
	ID_PEDIDOSTATUS INT PRIMARY KEY IDENTITY(1,1),
	DESCRICAO VARCHAR(30) NOT NULL UNIQUE,
	ID_USUARIOCADASTRO INT,
	DTCADASTRO DATETIME,
	ID_USUARIOALTERACAO INT,
	DTALTERACAO DATETIME
)

CREATE TABLE TB_PEDIDOTIPO
(
	ID_PEDIDOTIPO INT PRIMARY KEY IDENTITY(1,1),
	DESCRICAO VARCHAR(30) NOT NULL UNIQUE,
	ID_USUARIOCADASTRO INT,
	DTCADASTRO DATETIME,
	ID_USUARIOALTERACAO INT,
	DTALTERACAO DATETIME
)

INSERT INTO TB_PESSOATIPO(DESCRICAO, ID_USUARIOCADASTRO, DTCADASTRO) VALUES('Pessoa Física', 1, GETDATE())
INSERT INTO TB_PESSOATIPO(DESCRICAO, ID_USUARIOCADASTRO, DTCADASTRO) VALUES('Pessoa Jurídica', 1, GETDATE())
	
INSERT INTO TB_PESSOA(NOMECOMPLETO, NOMECONHECIDO, ID_PESSOATIPO, DTNASCIMENTO, SEXO) VALUES('ADMINISTRADOR', 'ADMINISTRADOR', 1, GETDATE(), 0)

INSERT INTO TB_USUARIO(LOGIN, SENHA, ID_PESSOA) VALUES('ADMIN', 'ADMIN', 1)

ALTER TABLE TB_PESSOA
	ADD FOREIGN KEY(ID_PESSOATIPO) REFERENCES TB_PESSOATIPO(ID_PESSOATIPO) ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE TB_PESSOA
	ADD FOREIGN KEY(ID_USUARIOALTERACAO) REFERENCES TB_USUARIO(ID_USUARIO) ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE TB_PESSOATIPO
	ADD FOREIGN KEY(ID_USUARIOALTERACAO) REFERENCES TB_USUARIO(ID_USUARIO) ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE TB_PESSOATIPO
	ADD FOREIGN KEY(ID_USUARIOCADASTRO) REFERENCES TB_USUARIO(ID_USUARIO) ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE TB_PESSOA
	ADD FOREIGN KEY(ID_USUARIOARQUIVACAO) REFERENCES TB_USUARIO(ID_USUARIO) ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE TB_CLIENTE
	ADD FOREIGN KEY(ID_PESSOA) REFERENCES TB_PESSOA(ID_PESSOA) ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE TB_CLIENTE
	ADD FOREIGN KEY(ID_USUARIOCADASTRO) REFERENCES TB_USUARIO(ID_USUARIO) ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE TB_ENDERECO
	ADD FOREIGN KEY(ID_PESSOA) REFERENCES TB_PESSOA(ID_PESSOA) ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE TB_ENDERECO
	ADD FOREIGN KEY(ID_USUARIOCADASTRO) REFERENCES TB_USUARIO(ID_USUARIO) ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE TB_ENDERECO
	ADD FOREIGN KEY(ID_USUARIOALTERACAO) REFERENCES TB_USUARIO(ID_USUARIO) ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE TB_CONTATO
	ADD FOREIGN KEY(ID_PESSOA) REFERENCES TB_PESSOA(ID_PESSOA) ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE TB_CONTATO
	ADD FOREIGN KEY(ID_CONTATOTIPO) REFERENCES TB_CONTATOTIPO(ID_CONTATOTIPO) ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE TB_CONTATO
	ADD FOREIGN KEY(ID_USUARIOCADASTRO) REFERENCES TB_USUARIO(ID_USUARIO) ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE TB_CONTATO
	ADD FOREIGN KEY(ID_USUARIOALTERACAO) REFERENCES TB_USUARIO(ID_USUARIO) ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE TB_CONTATOTIPO
	ADD FOREIGN KEY(ID_USUARIOALTERACAO) REFERENCES TB_USUARIO(ID_USUARIO) ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE TB_CONTATOTIPO
	ADD FOREIGN KEY(ID_USUARIOCADASTRO) REFERENCES TB_USUARIO(ID_USUARIO) ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE TB_USUARIO
	ADD FOREIGN KEY(ID_USUARIOCADASTRO) REFERENCES TB_USUARIO(ID_USUARIO) ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE TB_PERMISSAO
	ADD FOREIGN KEY(ID_USUARIOCADASTRO) REFERENCES TB_USUARIO(ID_USUARIO) ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE TB_PERMISSAO
	ADD FOREIGN KEY(ID_USUARIOALTERACAO) REFERENCES TB_USUARIO(ID_USUARIO) ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE TB_GRUPO
	ADD FOREIGN KEY(ID_GRUPOTIPO) REFERENCES TB_GRUPOTIPO(ID_GRUPOTIPO) ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE TB_GRUPO
	ADD FOREIGN KEY(ID_USUARIOCADASTRO) REFERENCES TB_USUARIO(ID_USUARIO) ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE TB_GRUPO
	ADD FOREIGN KEY(ID_USUARIOALTERACAO) REFERENCES TB_USUARIO(ID_USUARIO) ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE TB_GRUPOTIPO
	ADD FOREIGN KEY(ID_USUARIOALTERACAO) REFERENCES TB_USUARIO(ID_USUARIO) ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE TB_GRUPOTIPO
	ADD FOREIGN KEY(ID_USUARIOCADASTRO) REFERENCES TB_USUARIO(ID_USUARIO) ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE TB_GRUPOPERMISSAO
	ADD FOREIGN KEY(ID_GRUPO) REFERENCES TB_GRUPO(ID_GRUPO) ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE TB_GRUPOPERMISSAO
	ADD FOREIGN KEY(ID_PERMISSAO) REFERENCES TB_PERMISSAO(ID_PERMISSAO) ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE TB_DEPTOTECNICO
	ADD FOREIGN KEY(ID_USUARIOCADASTRO) REFERENCES TB_USUARIO(ID_USUARIO) ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE TB_DEPTOTECNICO
	ADD FOREIGN KEY(ID_USUARIOALTERACAO) REFERENCES TB_USUARIO(ID_USUARIO) ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE TB_PEDIDO
	ADD FOREIGN KEY(ID_PEDIDOTIPO) REFERENCES TB_PEDIDOTIPO(ID_PEDIDOTIPO) ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE TB_PEDIDO
	ADD FOREIGN KEY(ID_PEDIDOSTATUS) REFERENCES TB_PEDIDOSTATUS(ID_PEDIDOSTATUS) ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE TB_PEDIDO
	ADD FOREIGN KEY(ID_CLIENTE) REFERENCES TB_CLIENTE(ID_CLIENTE) ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE TB_PEDIDO
	ADD FOREIGN KEY(ID_TECNICO) REFERENCES TB_USUARIO(ID_USUARIO) ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE TB_PEDIDO
	ADD FOREIGN KEY(ID_DEPTOTECNICO) REFERENCES TB_DEPTOTECNICO(ID_DEPTOTECNICO) ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE TB_PEDIDO
	ADD FOREIGN KEY(ID_USUARIOCADASTRO) REFERENCES TB_USUARIO(ID_USUARIO) ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE TB_PEDIDO
	ADD FOREIGN KEY(ID_USUARIOCANCELAMENTO) REFERENCES TB_USUARIO(ID_USUARIO) ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE TB_PEDIDO
	ADD FOREIGN KEY(ID_USUARIOPGTOCONFIRMADO) REFERENCES TB_USUARIO(ID_USUARIO) ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE TB_PEDIDOTIPO
	ADD FOREIGN KEY(ID_USUARIOALTERACAO) REFERENCES TB_USUARIO(ID_USUARIO) ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE TB_PEDIDOTIPO
	ADD FOREIGN KEY(ID_USUARIOCADASTRO) REFERENCES TB_USUARIO(ID_USUARIO) ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE TB_PEDIDOSTATUS
	ADD FOREIGN KEY(ID_USUARIOALTERACAO) REFERENCES TB_USUARIO(ID_USUARIO) ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE TB_PEDIDOSTATUS
	ADD FOREIGN KEY(ID_USUARIOCADASTRO) REFERENCES TB_USUARIO(ID_USUARIO) ON UPDATE NO ACTION ON DELETE NO ACTION
