//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.1
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSWebCore.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSWebCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A descrição da regra de validação é inválida..
        /// </summary>
        internal static string BaseRuleInvalidDescription {
            get {
                return ResourceManager.GetString("BaseRuleInvalidDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome de propriedade da regra de validação é inválido..
        /// </summary>
        internal static string BaseRuleInvalidPropertyName {
            get {
                return ResourceManager.GetString("BaseRuleInvalidPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ^([a-zA-Z]{1}\S{1,})\s{1}(=|!=|&gt;|&lt;|&gt;=|&lt;=|LIKE)\s{1}(\d{1,}|&apos;[^&apos;\r\n]{0,}&apos;)$.
        /// </summary>
        internal static string BindingListViewExtendedFilterPattern {
            get {
                return ResourceManager.GetString("BindingListViewExtendedFilterPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A expressão de filtro é inválida..
        /// </summary>
        internal static string BindingListViewExtendedInvalidFilterString {
            get {
                return ResourceManager.GetString("BindingListViewExtendedInvalidFilterString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome da propriedade é inválido..
        /// </summary>
        internal static string BindingListViewExtendedInvalidPropertyName {
            get {
                return ResourceManager.GetString("BindingListViewExtendedInvalidPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível substituir um item por outro que já exista na coleção..
        /// </summary>
        internal static string BindingListViewExtendedItemAlreadyExists {
            get {
                return ResourceManager.GetString("BindingListViewExtendedItemAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A coleção não possui a propriedade &apos;{0}&apos;..
        /// </summary>
        internal static string BindingListViewExtendedPropertyNotFound {
            get {
                return ResourceManager.GetString("BindingListViewExtendedPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ?*+.|{}\[]()^$.
        /// </summary>
        internal static string BindingListViewExtendedRegexLiterals {
            get {
                return ResourceManager.GetString("BindingListViewExtendedRegexLiterals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A coleção não suporta localização de dados..
        /// </summary>
        internal static string BindingListViewExtendedSearchingNotSupported {
            get {
                return ResourceManager.GetString("BindingListViewExtendedSearchingNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A coleção não suporta ordenação de dados..
        /// </summary>
        internal static string BindingListViewExtendedSortingNotSupported {
            get {
                return ResourceManager.GetString("BindingListViewExtendedSortingNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ^((\d{2}.\d{3}.\d{3}/\d{4}-\d{2})|(\d{14}))$.
        /// </summary>
        internal static string CnpjPattern {
            get {
                return ResourceManager.GetString("CnpjPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ^((\d{3}.\d{3}.\d{3}-\d{2})|(\d{11}))$.
        /// </summary>
        internal static string CpfPattern {
            get {
                return ResourceManager.GetString("CpfPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A conexão com a base de dados não está aberta..
        /// </summary>
        internal static string DataAccessConnectionNotOpened {
            get {
                return ResourceManager.GetString("DataAccessConnectionNotOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O provedor de dados é inválido..
        /// </summary>
        internal static string DataAccessInvalidDataProvider {
            get {
                return ResourceManager.GetString("DataAccessInvalidDataProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome do parâmetro é inválido..
        /// </summary>
        internal static string DataAccessInvalidParameterName {
            get {
                return ResourceManager.GetString("DataAccessInvalidParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe um parâmetro com o nome &apos;{0}&apos;..
        /// </summary>
        internal static string DataAccessParameterNameAlreadyExists {
            get {
                return ResourceManager.GetString("DataAccessParameterNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A transação não foi inicializada..
        /// </summary>
        internal static string DataAccessTransactionNotInitialized {
            get {
                return ResourceManager.GetString("DataAccessTransactionNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O sentido de ordenação é inválido..
        /// </summary>
        internal static string PropertyComparerInvalidListSortDirection {
            get {
                return ResourceManager.GetString("PropertyComparerInvalidListSortDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O objeto do tipo &apos;{0}&apos; não possui a propriedade &apos;{1}&apos;..
        /// </summary>
        internal static string PropertyComparerInvalidPropertyDescriptor {
            get {
                return ResourceManager.GetString("PropertyComparerInvalidPropertyDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome da propriedade é inválido..
        /// </summary>
        internal static string RuleObjectInvalidPropertyName {
            get {
                return ResourceManager.GetString("RuleObjectInvalidPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a As regras de validação não foram criadas..
        /// </summary>
        internal static string RuleObjectRulesNotCreated {
            get {
                return ResourceManager.GetString("RuleObjectRulesNotCreated", resourceCulture);
            }
        }
    }
}
